services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: portfolio
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - portfolio-app
    restart: unless-stopped

  backend:
    container_name: portfolio-backend
    build:
      context: .
    image: portfolio-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/portfolio
      SPRING_DATASOURCE_USERNAME: cloud
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      APP_CORS_ALLOWED_ORIGINS: http://localhost:3000
    networks:
      - portfolio-app
    depends_on:
      - db

  frontend:
    container_name: portfolio-ui
    image: portfolio-ui:latest
    ports:
      - "3000:80"
    networks:
      - portfolio-app
    depends_on:
      - backend

networks:
  portfolio-app:
    driver: bridge

volumes:
  db: